matrix:
- name: Qml
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.text
  - pyspelling.filters.javascript
      jsdocs: true
      line_comments: true
      block_comments: true
      group_comments: true
      strings: true
  sources:
  - '**/*.qml'
  default_encoding: utf-8
