matrix:
- name: Qml
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.text:
    comments: true
  sources:
  - '**/*.qml'
  default_encoding: utf-8
