name: Build wasm app

on: push

jobs:
  buster:
    name: wasm build
    runs-on: ubuntu-latest
    container:
      image: guerra1994/qt-wasm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build 
        run: |
          git clone https://github.com/ossia/qml-remote.git
          cd qml-remote/
          mkdir /build
          cd /build
          qmake ..
          make

      - name: Zip
        shell: bash
        run: |
          tar -czvf /home/qml-remote/build.tar.gz /home/qml-remote/build
