name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.14.0
      name: Spellcheck
      with:
        config_path: config/.spellcheck.yml # path to configuration file here
        source_files: src/*
        task_name: Qml